name: CI

on:
  pull_request:
    paths:
      - src/**

jobs:
  matrix:
    name: Find packages
    runs-on: Ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch master from where the PR started
        run: git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*

      - name: Find packages
        id: find-packages
        run: echo "::set-output name=list::$(git diff --name-only origin/${{ github.base_ref }} HEAD | grep src/ | cut -d / -f 2 | sort | uniq | jq -R -s -c 'split("\n")[:-1]')"

    outputs:
      # Make the outputs accessible outside this job
      list: ${{ steps.find-packages.outputs.list }}

  build:
    needs: matrix
    name: Test
    runs-on: Ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        package: ${{ fromJson(needs.matrix.outputs.list) }}
        php: [ '8.0', '8.1', '8.2' ]
        strategy: [ 'highest', 'lowest' ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          extensions: swoole

      - name: Download dependencies
        uses: ramsey/composer-install@v2
        with:
          dependency-versions: ${{ matrix.strategy }}
          composer-options: --working-dir=src/${{ matrix.package }} --no-interaction --prefer-dist --optimize-autoloader

      - name: Run tests
        run: |
          cd src/${{ matrix.package }}
          ./vendor/bin/phpunit

